---
- hosts: tag_Name_EC2
  connection: ssh
  become: true
  tasks:
  - name: installing apache server
    apt:
      name: apache2
      update_cache: true
      state: present
  - name: create webpage
    copy: 
      src: /home/ubuntu/demos/index.html
      dest: /var/www/html/index.html

  - name: start apache
    service:
      name: apache2
      state: started